/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminChatsRouteImport } from './routes/admin/chats'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/admin/chats',
  path: '/admin/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/services'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/services'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/chats'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/services'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/admin/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
